name: 'Run detekt with review dog'
description: '🐶 Run detekt with reviewdog on pull requests to enforce best practices'
author: 'Alexey Egin (alaegin)'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  docker_registry:
    description: 'Name of Docker registry (e.g., docker.io, ghcr.io)'
    required: false
    default: 'docker.io'
  docker_username:
    description: 'Docker registry username'
    required: false
    default: ''
  docker_token:
    description: 'Docker registry PAT token'
    required: false
    default: ''
  reviewdog_level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'error'
  reviewdog_filter:
    description: 'Filter mode for reviewdog [added,diff_context,file,nofilter]'
    required: false
    default: 'added'
  reviewdog_reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: 'github-pr-check'
  detekt_config:
    description: 'yml detekt config'
    required: false
    default: 'default-detekt-config.yml'
  detekt_excludes:
    description: 'Globing patterns describing paths to exclude from the analysis.'
    required: false
    default: '**/build/**,**/.idea/**'
  fail_on_error:
    description: |
      Fails the current check if any error was found [true/false]
      Default is false.
    required: false
    default: 'true'
  detekt_plugins:
    description: |
      Additional plugins for detekt.
      Should be defined with comma separation
      Example: 'path/1.jar,path/2.jar'
    required: false
  detekt_baseline:
    description: 'Provides baseline.xml file to detekt'
    required: false
  detekt_parallel:
    description: 'Executes detekt in parallel'
    required: false
  detekt_build_upon_default_config:
    description: 'Preconfigures detekt with a bunch of rules and some opinionated defaults 
      for you. Allows additional provided configurations to override the 
      defaults.'
    required: false
  detekt_all_rules:
    description: 'Activates all available (even unstable) rules.'
    required: false
  detekt_input:
    description: |
      'Specific inputs for detekt (the --input argument for detekt-cli)'
      Example: 'path/to/dir1,path/to/dir2'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Run detekt with reviewdog
      uses: docker://Dockerfile
      with:
        args:
          - ${{ inputs.github_token }}
          - ${{ inputs.reviewdog_level }}
          - ${{ inputs.reviewdog_filter }}
          - ${{ inputs.reviewdog_reporter }}
          - ${{ inputs.detekt_config }}
          - ${{ inputs.detekt_excludes }}
          - ${{ inputs.fail_on_error }}
          - ${{ inputs.detekt_plugins }}
          - ${{ inputs.detekt_baseline }}
          - ${{ inputs.detekt_parallel }}
          - ${{ inputs.detekt_build_upon_default_config }}
          - ${{ inputs.detekt_all_rules }}
          - ${{ inputs.detekt_input }}
branding:
  icon: 'check-square'
  color: 'orange'
